FROM quay.io/jlebon/pet:f43

LABEL org.opencontainers.image.source="https://github.com/jbtrystram/toolbox"

COPY extra-packages chezmoi.sh helix.sh misc-tools.sh /setup/

RUN dnf -y install $(</setup/extra-packages) \
    && dnf clean all \
    && /setup/chezmoi.sh \
    && /setup/helix.sh \
    && /setup/misc-tools.sh \
    && rm -rf /setup

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout

# Setup host-runner script and symlinks
COPY host-runner /usr/local/bin/host-runner
RUN bins=( \
    "ujust" \
    "firefox" \
    "flatpak" \
    "podman" \
    "systemctl" \
    "virsh" \
    "virt-install" \
    "xdg-open" \
    "gitsign" \
    ); \
    for f in "${bins[@]}"; do \
        ln -s host-runner /usr/local/bin/$f;\
    done
