#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat 1>&2 <<'EOF'
Usage: host [-e foo=bar] [COMMANDS]
       
  Execute COMMANDS on the host shell. If no argument is provided, will spawn a bash shell on the host.

  The following options are available:

  -e        Inject environnement variable. Can be repeated.
  -h        Print this help

EOF
}

if [[ ! -f "/run/.containerenv" ]]; then
  echo "This must be run from a container"
  exit 1
fi  


ADDITIONNAL_ENV_VARS=
while getopts 'he:' FLAG; do
  case "$FLAG" in
    h)
      print_help
      exit 0
      ;;
    e)
      ADDITIONNAL_ENV_VARS+="--env=${OPTARG} "
      ;;
    ?)
      echo "error: unrecognized option: $FLAG"
      ;;
    esac
done    
shift "$((OPTIND -1))"

ADDITIONNAL_ENV_VARS+=NO_TOOLBOX=true
COMMANDS=

# No commands, launch a shell
if [ $# -eq 0 ]; then
    COMMANDS=bash
else
  COMMANDS=( "$@" )
fi    

flatpak-spawn --host --env="${ADDITIONNAL_ENV_VARS}" "${COMMANDS[@]}"
