FROM quay.io/fedora/fedora-sericea:39

LABEL maintainer=jbtrystram

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# RUN sudo rpm-ostree update \
#       --uninstall rpmfusion-free-release \
#       --uninstall rpmfusion-nonfree-release \
#       --install rpmfusion-free-release \
#       --install rpmfusion-nonfree-release

COPY extra-packages /opt/

RUN rpm-ostree install -y $(</opt/extra-packages)