FROM quay.io/jbtrystram/toolbox:latest

RUN dnf install -y gcc openssl openssl-devel cmake gcc-c++
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y 
ENV PATH "$PATH:/root/.cargo/bin"

LABEL org.opencontainers.image.source="https://github.com/jbtrystram/toolbox/rust"

COPY extra-packages /opt/

RUN dnf install -y $(</opt/extra-packages)