# allow a switch between main and and nvidia
ARG VARIANT=main
FROM ghcr.io/ublue-os/kinoite-$VARIANT:39

LABEL maintainer=jbtrystram
# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY extra-packages /tmp/

RUN rpm-ostree install -y $(</tmp/extra-packages) \
  && systemctl enable libvirtd.socket \
  && ostree container commit
